// Stable item IDs are saved in players' inventories. Keep existing entries intact.
export const BODY_STYLES = Object.freeze([
  "jeep",
  "buggy",
  "van",
  "sport",
  "pickup",
  "roadster",
  "rally",
]);
export const TRAIL_STYLES = Object.freeze([
  "none",
  "dust",
  "bubbles",
  "stars",
  "rainbow",
  "leaves",
  "sparks",
  "hearts",
  "snow",
  "petals",
  "embers",
  "diamonds",
  "confetti",
]);
export const SPRAY_STYLES = Object.freeze([
  "wave",
  "smile",
  "flower",
  "heart",
  "lightning",
  "crown",
  "star",
  "moon",
  "sun",
  "leaf",
  "paw",
  "coffee",
  "music",
  "peace",
  "rocket",
  "cloud",
  "clover",
  "diamond",
  "flag",
  "planet",
]);

const originalItems = [
  {
    id: "body-starter",
    type: "body",
    rarity: "common",
    name: "처음의 지프",
    color: "#efaa8c",
    style: "jeep",
    starter: true,
  },
  {
    id: "trail-none",
    type: "trail",
    rarity: "common",
    name: "가볍게 달리기",
    color: "#ffffff",
    style: "none",
    starter: true,
  },
  {
    id: "spray-wave",
    type: "spray",
    rarity: "common",
    name: "반가워!",
    color: "#80a781",
    style: "wave",
    starter: true,
  },
  {
    id: "body-cream",
    type: "body",
    rarity: "common",
    name: "바닐라 지프",
    color: "#eee1b6",
    style: "jeep",
  },
  {
    id: "body-mint",
    type: "body",
    rarity: "common",
    name: "민트 버기",
    color: "#a2c9b0",
    style: "buggy",
  },
  {
    id: "body-peach",
    type: "body",
    rarity: "common",
    name: "피치 밴",
    color: "#e8a18a",
    style: "van",
  },
  {
    id: "trail-dust",
    type: "trail",
    rarity: "common",
    name: "뽀얀 먼지",
    color: "#e0d8bd",
    style: "dust",
  },
  {
    id: "spray-smile",
    type: "spray",
    rarity: "common",
    name: "싱긋",
    color: "#e4b564",
    style: "smile",
  },
  {
    id: "spray-flower",
    type: "spray",
    rarity: "common",
    name: "작은 꽃",
    color: "#eba99b",
    style: "flower",
  },
  {
    id: "body-ocean",
    type: "body",
    rarity: "rare",
    name: "오션 스포츠",
    color: "#5f9bcc",
    style: "sport",
  },
  {
    id: "body-sky",
    type: "body",
    rarity: "rare",
    name: "소다 밴",
    color: "#7ebbd0",
    style: "van",
  },
  {
    id: "trail-bubbles",
    type: "trail",
    rarity: "rare",
    name: "소다 버블",
    color: "#89c9e8",
    style: "bubbles",
  },
  {
    id: "spray-heart",
    type: "spray",
    rarity: "rare",
    name: "마음을 남겨요",
    color: "#ef94b8",
    style: "heart",
  },
  {
    id: "body-lavender",
    type: "body",
    rarity: "epic",
    name: "라벤더 레이서",
    color: "#b095d8",
    style: "sport",
  },
  {
    id: "trail-stars",
    type: "trail",
    rarity: "epic",
    name: "별빛 산책",
    color: "#c1a1ef",
    style: "stars",
  },
  {
    id: "spray-lightning",
    type: "spray",
    rarity: "epic",
    name: "찌릿!",
    color: "#ab82df",
    style: "lightning",
  },
  {
    id: "body-gold",
    type: "body",
    rarity: "legendary",
    name: "골든 아워",
    color: "#eac45d",
    style: "sport",
  },
  {
    id: "trail-rainbow",
    type: "trail",
    rarity: "legendary",
    name: "무지개 꼬리",
    color: "#f4cf68",
    style: "rainbow",
  },
  {
    id: "spray-crown",
    type: "spray",
    rarity: "legendary",
    name: "오늘의 왕관",
    color: "#f0c64f",
    style: "crown",
  },
];

const variants = (type, rows) =>
  rows.map(([id, name, rarity, color, style]) => ({
    id: `${type}-${id}`,
    type,
    rarity,
    name,
    color,
    style,
  }));

export const ITEMS = Object.freeze(
  [
    ...originalItems,
    ...variants("body", [
      ["matcha", "말차 지프", "common", "#91ab76", "jeep"],
      ["cocoa", "코코아 지프", "common", "#aa8971", "jeep"],
      ["sand", "모래빛 버기", "common", "#d4bd87", "buggy"],
      ["denim", "데님 버기", "common", "#7797b1", "buggy"],
      ["butter", "버터 밴", "common", "#e6cc79", "van"],
      ["rose", "로즈밀크 밴", "common", "#dba8b7", "van"],
      ["garden", "정원사의 픽업", "common", "#8fac8d", "pickup"],
      ["apricot", "살구 픽업", "common", "#e1a374", "pickup"],
      ["cloud", "구름 로드스터", "common", "#d6ded8", "roadster"],
      ["brick", "벽돌빛 랠리", "common", "#bd7b67", "rally"],
      ["lake", "호숫가 지프", "rare", "#76aeba", "jeep"],
      ["iris", "아이리스 버기", "rare", "#939cc9", "buggy"],
      ["lemon", "레몬 스포츠", "rare", "#d9d27b", "sport"],
      ["cherry", "체리 스포츠", "rare", "#c87990", "sport"],
      ["surf", "서퍼의 픽업", "rare", "#64b8ae", "pickup"],
      ["marine", "마린 로드스터", "rare", "#679bc5", "roadster"],
      ["moss", "이끼숲 랠리", "rare", "#728e71", "rally"],
      ["plum", "자두빛 밴", "rare", "#a486b3", "van"],
      ["twilight", "황혼의 지프", "epic", "#b081b6", "jeep"],
      ["orchid", "난초빛 로드스터", "epic", "#bd8cbe", "roadster"],
      ["comet", "혜성 랠리", "epic", "#889bcc", "rally"],
      ["midnight", "미드나잇 스포츠", "epic", "#626e9b", "sport"],
      ["aurora", "오로라 픽업", "epic", "#8ec1b9", "pickup"],
      ["honey", "허니 로드스터", "legendary", "#edc265", "roadster"],
      ["champion", "챔피언 랠리", "legendary", "#d4aa55", "rally"],
      ["moonstone", "문스톤 밴", "legendary", "#e7e3cd", "van"],
      ["sunrise", "일출 스포츠", "legendary", "#eaa873", "sport"],
    ]),
    ...variants("trail", [
      ["sandy", "모래 발자국", "common", "#d5b77f", "dust"],
      ["chalk", "분필 구름", "common", "#e6e4d1", "dust"],
      ["spring", "봄잎 산책", "common", "#99bc77", "leaves"],
      ["autumn", "가을잎 산책", "common", "#c7965f", "leaves"],
      ["rose-petals", "장미 꽃잎", "common", "#d6a1ab", "petals"],
      ["daisy-petals", "데이지 꽃잎", "common", "#e8dd9d", "petals"],
      ["peach-papers", "복숭아 종이조각", "common", "#e1aa8d", "confetti"],
      ["mint-papers", "민트 종이조각", "common", "#a3c6b4", "confetti"],
      ["copper", "구리빛 불티", "common", "#cda07c", "sparks"],
      ["tea", "찻잎 바람", "common", "#899f6a", "leaves"],
      ["seafoam", "바다 거품", "rare", "#93cfbc", "bubbles"],
      ["pink-soda", "핑크 소다", "rare", "#e2a5c1", "bubbles"],
      ["first-snow", "첫눈 소식", "rare", "#dae8ed", "snow"],
      ["ice-sparks", "얼음 불꽃", "rare", "#82c4df", "sparks"],
      ["blue-hearts", "파란 고백", "rare", "#82b0d6", "hearts"],
      ["cherry-blossom", "벚꽃 드라이브", "rare", "#f0b6c5", "petals"],
      ["lilac-papers", "라일락 축제", "rare", "#b4a4d4", "confetti"],
      ["moon-snow", "달빛 눈송이", "epic", "#c3cbe9", "snow"],
      ["purple-hearts", "보랏빛 설렘", "epic", "#bd95da", "hearts"],
      ["amethyst", "자수정 조각", "epic", "#b198df", "diamonds"],
      ["campfire", "모닥불 꼬리", "epic", "#f0b06c", "embers"],
      ["stargazer", "별을 줍는 밤", "epic", "#8faee1", "stars"],
      ["golden-stars", "금빛 별똥별", "legendary", "#f0d184", "stars"],
      ["diamond-dust", "다이아몬드 산책", "legendary", "#dceff0", "diamonds"],
      ["phoenix", "불사조의 깃털", "legendary", "#efa275", "embers"],
      ["festival", "무지개 축제", "legendary", "#e9c381", "confetti"],
    ]),
    ...variants("spray", [
      ["little-star", "나의 작은 별", "common", "#e7bc6e", "star"],
      ["cat-paw", "고양이 다녀감", "common", "#c89a82", "paw"],
      ["coffee-break", "커피 한 잔", "common", "#ad8870", "coffee"],
      ["green-leaf", "초록 한 잎", "common", "#95b075", "leaf"],
      ["good-day", "오늘도 맑음", "common", "#e4b974", "sun"],
      ["fluffy", "뭉게뭉게", "common", "#aac4cd", "cloud"],
      ["hello-note", "콧노래", "common", "#b5a3c9", "music"],
      ["peace-sign", "사이좋게 지내요", "common", "#9ab287", "peace"],
      ["lucky-leaf", "작은 행운", "common", "#81ac80", "clover"],
      ["picnic-flag", "여기서 만나요", "common", "#cf9a80", "flag"],
      ["blue-moon", "파란 달", "rare", "#89aaca", "moon"],
      ["paper-rocket", "꿈꾸는 로켓", "rare", "#80b8c6", "rocket"],
      ["pink-paw", "젤리 발도장", "rare", "#dfa6bc", "paw"],
      ["mint-note", "민트 멜로디", "rare", "#88bdb1", "music"],
      ["cloud-nine", "구름 위 산책", "rare", "#97b7dd", "cloud"],
      ["blue-gem", "파란 보석", "rare", "#7aa9d4", "diamond"],
      ["lucky-blue", "오늘은 운 좋은 날", "rare", "#79b4af", "clover"],
      ["pink-peace", "분홍빛 평화", "rare", "#d6a2c6", "peace"],
      ["purple-planet", "우리의 작은 행성", "epic", "#ad93d1", "planet"],
      ["night-moon", "잘 자요, 달님", "epic", "#b5abd8", "moon"],
      ["cosmic-rocket", "우주로 놀러 가자", "epic", "#a5a2dd", "rocket"],
      ["violet-gem", "보랏빛 보물", "epic", "#b090d2", "diamond"],
      ["lilac-star", "소원을 담은 별", "epic", "#c0a4d7", "star"],
      ["purple-flag", "우리 팀 최고", "epic", "#a998c5", "flag"],
      ["sun-king", "햇살의 주인", "legendary", "#e9c26c", "sun"],
      ["golden-planet", "황금빛 궤도", "legendary", "#e5bd79", "planet"],
      ["golden-clover", "네 잎의 기적", "legendary", "#d5bb6a", "clover"],
      ["royal-heart", "가장 빛나는 마음", "legendary", "#e3b979", "heart"],
    ]),
  ].map((item) => Object.freeze(item)),
);
